name: CI/CD Pipeline

on: [push]

jobs:
  showData:
    runs-on: ubuntu-latest
    steps:
      - name: Show data
        run: |
          echo "Usuario: ${{ github.actor }}"
          echo "Repositorio: ${{ github.repository }}"
          echo "Rama: ${{ github.ref_name }}"
